# SPDX-FileCopyrightText: 2010 - 2024 the Friendica project
#
# SPDX-License-Identifier: CC0-1.0

# The phpmd check is just triggered for PRs and pushes to non-stable branches of Friendica
when:
  branch:
    exclude: [ stable ]
  event: [ pull_request, push ]

steps:
  phpmd:
    image: friendicaci/php8.3:php8.3.3
    commands:
      - mkdir addon
      - ./bin/composer.phar install
      - ./bin/composer.phar run phpmd
